### ISSUE TITLE
shouldn't manipulate Harfbuzz blobs without a blob

### ISSUE THREAD

**Issue by classilla** [classilla/tenfourfox#309]
Uplifted from http://tenfourfox.tenderapp.com/discussions/problems/7199-a-user-of-the-powerpc_g4_macosx1058-problems

The provided URL http://naspecaudio.com/wire-world/wire-world-brand-story/ crashes on both 10.4 and 10.5, so it is a little more complicated than issue 261. In a debug build,

    Size of ufjZIdvmW-QtqQu9TLDZLTNg== font table directory: 236
    Tables: Glyph count mismatch: ATSFontGetGlyphCount returned 248; FOCountGlyphs returned 8324.
    
    Program received signal EXC_BAD_ACCESS, Could not access memory.
    Reason: KERN_PROTECTION_FAILURE at address: 0x00000034
    hb_blob_get_length (blob=0x0) at /Volumes/BruceDeuce/src/esr38d/gfx/harfbuzz/src/hb-blob.cc:332
    332     }

**Comment by classilla** [comment]
(gdb) bt
#0  hb_blob_get_length (blob=0x0) at /Volumes/BruceDeuce/src/esr38d/gfx/harfbuzz/src/hb-blob.cc:332
#1  0x0875ae30 in gfxHarfBuzzShaper::LoadHmtxTable (this=0x3e0b51d0) at gfxHarfBuzzShaper.cpp:1231
#2  0x0875b054 in gfxHarfBuzzShaper::Initialize (this=0x3e0b51d0) at gfxHarfBuzzShaper.cpp:1196
#3  0x087716ec in gfxHarfBuzzShaper::ShapeText (this=0x3e0b51d0, aContext=0x2fe3f3d0, aText=0xefff6626, aOffset=0, aLength=5, aScript=17, aVertical=false, aShapedText=0x39de3970) at gfxHarfBuzzShaper.cpp:1322
#4  0x0873e6e8 in gfxFont::ShapeText (this=0x39df2b10, aContext=0x2fe3f3d0, aText=0xefff6626, aOffset=0, aLength=5, aScript=17, aVertical=false, aShapedText=0x39de3970) at gfxFont.cpp:2521
#5  0x08753dc8 in _ZN7gfxFont13GetShapedWordIDsEEP13gfxShapedWordP10gfxContextPKT_jjibijP18gfxTextPerfMetrics (this=0x39df2b10, aContext=0x2fe3f3d0, aText=0xefff6626, aLength=5, aHash=<value temporarily unavailable, due to optimizations>, aRunScript=17, aVertical=false, aAppUnitsPerDevUnit=60, aFlags=0, aTextPerf=0x0) at gfxFont.cpp:2430
#6  0x0874316c in SplitAndInitTextRun<char16_t> (this=0x39df2b10, aContext=0x2fe3f3d0, aTextRun=0x39dafdb0, aString=0xefff6626, aRunStart=1, aRunLength=5, aRunScript=17, aVertical=false) at gfxFont.cpp:2813
#7  0x08779590 in _ZN12gfxFontGroup13InitScriptRunIDsEEvP10gfxContextP10gfxTextRunPKT_jjiP22gfxMissingFontRecorder (this=0x39de2d80, aContext=0x2fe3f3d0, aTextRun=0x39dafdb0, aString=0xefff6624, aOffset=0, aLength=6, aRunScript=17, aMFR=0x0) at gfxTextRun.cpp:2440
#8  0x08779d64 in _ZN12gfxFontGroup11InitTextRunIDsEEvP10gfxContextP10gfxTextRunPKT_jP22gfxMissingFontRecorder (this=0x5, aContext=0x1, aTextRun=0x1, aString=0x39df2b10, aLength=27, aMFR=0x0) at gfxTextRun.cpp:2264
#9  0x08772c18 in gfxFontGroup::MakeTextRun (this=0x39dafdb0, aString=0xefff6624, aLength=27, aParams=0x1, aFlags=22283520, aMFR=0x0) at gfxTextRun.cpp:2124

**Comment by classilla** [comment]
Wallpapered by having Harfbuzz return length zero for null pointers instead of smoking out everywhere a null blob could get.

URLs now blocked:

Tables: Font blacklist checking: http://fonts.gstatic.com/ea/notosansjapanese/v6/NotoSansJP-Regular.woff2
Font blacklist checking: http://fonts.gstatic.com/ea/notosansjapanese/v6/NotoSansJP-Regular.woff
Warning: TenFourFox blocking ATSUI-incompatible webfont http://fonts.gstatic.com/ea/notosansjapanese/v6/NotoSansJP-Regular.woff.
Font blacklist checking: http://fonts.gstatic.com/ea/notosansjapanese/v6/NotoSansJP-Regular.otf
Warning: TenFourFox blocking ATSUI-incompatible webfont http://fonts.gstatic.com/ea/notosansjapanese/v6/NotoSansJP-Regular.otf.
Size of Verdana-Bold font table directory: 348
Tables: Size of Helvetica-Bold font table directory: 316
Tables: Font blacklist checking: http://fonts.gstatic.com/ea/notosansjapanese/v6/NotoSansJP-Bold.woff2
Font blacklist checking: http://fonts.gstatic.com/ea/notosansjapanese/v6/NotoSansJP-Bold.woff
Warning: TenFourFox blocking ATSUI-incompatible webfont http://fonts.gstatic.com/ea/notosansjapanese/v6/NotoSansJP-Bold.woff.
Font blacklist checking: http://fonts.gstatic.com/ea/notosansjapanese/v6/NotoSansJP-Bold.otf
Warning: TenFourFox blocking ATSUI-incompatible webfont http://fonts.gstatic.com/ea/notosansjapanese/v6/NotoSansJP-Bold.otf.

**Comment by classilla** [comment]
Shipp'd
