### ISSUE TITLE
Correctness fix: make IsBackgroundFinalized agree with what we actually do

### ISSUE THREAD

**Issue by classilla** [classilla/tenfourfox#479]
Since TenFourFox 17 we have disabled background finalization of all tenured objects for better/more determinative gc performance on uniprocessor systems, which is the majority of our machines. (Nursery objects, when the nursery was introduced, are allowed to finalize in the background.)

`IsBackgroundFinalized` doesn't know this (in `jsgc.h`) and we get a weird but consistent assert in DEBUG builds on http://ferut.ca/my-story/ . The assert is bogus because the finalization _must_ be the same, but it would be better to fix this function rather than the assert in case we change things later.

Backtrace in DEBUG (the test site does not assert in opt builds):

```
#0  0x0c195f8c in JSObject::swap (cx=0x463a30, a=<incomplete type>, b=<incomplete type>) at jsobj.cpp:1555
#1  0x0c1e7000 in js::RemapWrapper (cx=0x463a30, wobjArg=<value temporarily unavailable, due to optimizations>, newTargetArg=<value temporarily unavailable, due to optimizations>) at proxy/CrossCompartmentWrapper.cpp:542
#2  0x0c1e7c08 in js::RecomputeWrappers (cx=0x463a30, sourceFilter=@0xefff1958, targetFilter=<value temporarily unavailable, due to optimizations>) at proxy/CrossCompartmentWrapper.cpp:617
#3  0x092d7d80 in nsPrincipal::SetDomain (this=<value temporarily unavailable, due to optimizations>, aDomain=<value temporarily unavailable, due to optimizations>) at nsPrincipal.cpp:329
#4  0x0a446574 in nsHTMLDocument::SetDomain (this=0x3e20d000, aDomain=<value temporarily unavailable, due to optimizations>, rv=@0xefff1c98) at nsHTMLDocument.cpp:990
#5  0x0a0853c8 in set_domain (cx=0x40dbc800, obj=<value temporarily unavailable, due to optimizations>, self=0x3e20d000, args=<value temporarily unavailable, due to optimizations>) at HTMLDocumentBinding.cpp:53
#6  0x0a14c664 in mozilla::dom::GenericBindingSetter (cx=0x40dbc800, argc=<value temporarily unavailable, due to optimizations>, vp=<value temporarily unavailable, due to optimizations>) at BindingUtils.cpp:2711
#7  0x0c29c250 in js::CallJSNative (cx=0x40dbc800, native=0xa14c560 <mozilla::dom::GenericBindingSetter(JSContext*, unsigned int, JS::Value*)>, args=@0xefff1e98) at jscntxtinlines.h:362
#8  0x0c295144 in js::Invoke (cx=0x40dbc800, args=@0xefff1e98, construct=NO_CONSTRUCT) at Interpreter.cpp:444
#9  0x0c295fa0 in js::Invoke (cx=0x40dbc800, thisv=@0xefff22b0, fval=@0xefff1f98, argc=1, argv=0xefff2010, rval=<value temporarily unavailable, due to optimizations>) at Interpreter.cpp:496
```

**Comment by classilla** [comment]
This first idea didn't work, and conflicted badly with some other patches.

**Comment by classilla** [comment]
I think now the best thing is actually to remove the assert after all. It really doesn't apply to us.
